In [1]:
import gym

In [2]:
env = gym.make("ALE/Tetris-v5")


In [3]:
env.action_space

Discrete(18)

In [4]:
env.observation_space.dtype

dtype('uint8')

In [5]:
env.observation_space.shape

(210, 160, 3)

In [6]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [7]:
env.observation_space.sample()

array([[[133, 251,  37],
        [ 38, 247, 198],
        [100,  80,  20],
        ...,
        [ 76,  92,  54],
        [ 70, 167, 243],
        [177,   8, 209]],

       [[ 43,  26,  38],
        [187, 237, 115],
        [ 13,  31,  10],
        ...,
        [ 63, 135, 123],
        [ 44, 121,  81],
        [ 66, 226,  62]],

       [[147,  86,  91],
        [211, 227,  43],
        [179, 150,  15],
        ...,
        [ 14, 236,  24],
        [212, 112,   5],
        [ 38, 201, 194]],

       ...,

       [[111, 172, 200],
        [101, 218,  86],
        [203, 132,   7],
        ...,
        [113,  97, 191],
        [240, 236, 152],
        [237, 227, 161]],

       [[ 66,  64,  95],
        [ 41,  18, 164],
        [177, 247, 217],
        ...,
        [205,  96, 150],
        [ 25,   8, 144],
        [ 26, 242, 189]],

       [[235, 132,  68],
        [117,  20,  10],
        [ 89, 233, 133],
        ...,
        [ 18, 251, 243],
        [111, 170, 114],
        [ 63, 222, 108]]

In [8]:
env.reset()
env.render()

C:\Users\d7757\miniconda3\envs\_gym\lib\site-packages\gym\envs\atari\environment.py:255: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(
C:\Users\d7757\miniconda3\envs\_gym\lib\site-packages\pyglet\image\codecs\wic.py:289: UserWarning: [WinError -2147417850] 執行緒模式設定後就不能再變更它。
  warnings.warn(str(err))


True

In [9]:
env.close()

In [14]:
G = 0
for i_episode in range(1):
    observation = env.reset()
    t = 0
    while True:
        t += 1
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        G += reward
        print(f"Reward: {reward}, Total: {G}")
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 50 132  50]
  [ 50 132  50]
  [ 50 132  50]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]
Reward: 0.0, Total: 0.0
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [ 50 132  50]
  [ 50 132  50]
  [ 50 132  50]]

 ...

 [[  0   0   0]
  [  0   0  

In [3]:
import numpy as np
from collections import defaultdict

In [40]:
def new_explored_state():
    return np.full((18, ), 0.)

Q = defaultdict(new_explored_state)

In [25]:
def totuple(a):
    try:
        return tuple(totuple(i) for i in a)
    except TypeError:
        return a

In [23]:
env.close()

In [41]:
episodes = 50
G = 0

alpha = 0.618

for episode in range(1,episodes+1):
    done = False
    G, reward = 0,0

    state = env.reset().reshape((100800,))
    state = tuple(state)
    print(f"Episode: {episode+1}")
    print(f"Initial state Q: {Q[state]}")
    counter = 0
    firstState = state
    done = False
    while not done:
        env.render()
        action = np.argmin(Q[state])  #1
        state2, reward, done, info = env.step(action) #2
        state2.resize((100800,))
        state2 = tuple(state2)
        reward += 1.
        Q[state][action] += alpha * (reward + np.min(Q[state2]) - Q[state][action]) #3

        counter += 1
        G += reward
        state = state2
    print("Solved in {} Steps with a total reward of {}".format(counter, G))
    print(f"Final state Q: {Q[state]}")
    env.close()    
    


Initial state Q: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


C:\Users\d7757\miniconda3\envs\_gym\lib\site-packages\gym\envs\atari\environment.py:255: UserWarning: WARN: We strongly suggest supplying `render_mode` when constructing your environment, e.g., gym.make(ID, render_mode='human'). Using `render_mode` provides access to proper scaling, audio support, and proper framerates.
  logger.warn(


Solved in 354 Steps with a total reward of 354.0
Final state Q: [0.618 0.618 0.618 0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.   ]
Initial state Q: [0.618 0.618 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.   ]
Solved in 399 Steps with a total reward of 399.0
Final state Q: [0.618 0.618 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.   ]
Initial state Q: [0.618 0.618 0.618 0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.   ]
Solved in 347 Steps with a total reward of 347.0
Final state Q: [0.618 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
 0.    0.    0.    0.    0.    0.   ]
